// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesApiSample.DAL.Framework;

#nullable disable

namespace MoviesApiSample.DAL.Migrations
{
    [DbContext(typeof(MoviesApiSampleDbContex))]
    [Migration("20250407064551_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesApiSample.Models.ActorNamespace.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorMovieId")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActorMovieId");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("MoviesApiSample.Models.ActorNamespace.ActorMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ActorMovies");
                });

            modelBuilder.Entity("MoviesApiSample.Models.DirectorNamespace.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DirectorMovieId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("MoviesApiSample.Models.DirectorNamespace.DirectorMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId")
                        .IsUnique();

                    b.ToTable("DirectorMovies");
                });

            modelBuilder.Entity("MoviesApiSample.Models.MovieNamespace.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorMovieId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectorMovieId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActorMovieId");

                    b.HasIndex("DirectorMovieId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MoviesApiSample.Models.ActorNamespace.Actor", b =>
                {
                    b.HasOne("MoviesApiSample.Models.ActorNamespace.ActorMovie", "ActorMovie")
                        .WithMany("Actors")
                        .HasForeignKey("ActorMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorMovie");
                });

            modelBuilder.Entity("MoviesApiSample.Models.DirectorNamespace.DirectorMovie", b =>
                {
                    b.HasOne("MoviesApiSample.Models.DirectorNamespace.Director", "Director")
                        .WithOne("DirectorMovie")
                        .HasForeignKey("MoviesApiSample.Models.DirectorNamespace.DirectorMovie", "DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("MoviesApiSample.Models.MovieNamespace.Movie", b =>
                {
                    b.HasOne("MoviesApiSample.Models.ActorNamespace.ActorMovie", "ActorMovie")
                        .WithMany("Movies")
                        .HasForeignKey("ActorMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesApiSample.Models.DirectorNamespace.DirectorMovie", "DirectorMovie")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorMovie");

                    b.Navigation("DirectorMovie");
                });

            modelBuilder.Entity("MoviesApiSample.Models.ActorNamespace.ActorMovie", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MoviesApiSample.Models.DirectorNamespace.Director", b =>
                {
                    b.Navigation("DirectorMovie")
                        .IsRequired();
                });

            modelBuilder.Entity("MoviesApiSample.Models.DirectorNamespace.DirectorMovie", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
